### PR TITLE
Add support for annotations to KlassIdentifier refs. Issue#95

### LINKED ISSUE #95: Add support for @JvmSuppressWildcards/ Annotations for types.
Input: 
```
interface Something

class MyClass(
    list: List<@JvmSuppressWildcards Something>
)
```
Outputs: 
`found unsupported ast node 'KlassAnnotation(identifier=[KlassIdentifier(identifier=JvmSuppressWildcards ...`

**_Need:_** When using Kotlin & Java together, we need to often mark Generic types using `@JvmSuppressWildcards` to strip out `? extend Somthing` when kotlin code is compiled and used from Java. 
This is especially needed when using [Dagger with Kotlin](https://github.com/google/dagger/issues/900#issuecomment-359630229). 

Could you please add support for this? 
Thanks in advance :)

### PR DESCRIPTION
**Pull request by birajpatel**
Fixes : https://github.com/kotlinx/ast/issues/95

### CODE REVIEW

**Comment by birajpatel** [comment]
@drieks Please review 😃.

**Comment by drieks** [comment]
Hi @birajpatel , thank you very very much! Your pull request looks very good! Sadly, there is a problem with the build system. To fix this, I want to move the build to gitlab actions. I already migrated https://github.com/drieks/antlr-kotlin in this way (this is a dependency used by kotlinx.ast). The release action is working fine: https://github.com/drieks/antlr-kotlin/actions/runs/4536723459/jobs/8409480096, but the publication to maven cental is not working (https://github.com/kotlinx/ast/issues/89)

When this is fixed, I can use almost the same action for kotlinx.ast to upload it to maven central. after this, the build should be stable and this pull request should be able to build.

I'm really very sorry that the build is broken and that's why the pull request can't be merged at the moment :(

**Comment by birajpatel** [comment]
@drieks Oh, thats really sad, Actually we are using this library for one of our internal tools and merging is this fix will unblock some pending things. (Because without my fix above the parser just fails to parse the file).
Please try to help ASAP 😄 🙏  I saw many other folks are also awaiting the mavenCentral release. 🙏

**Comment by renatacmn** [comment]
Hey @drieks! Any news on this? I'm also interested in this fix 👀

**Comment by aaronfodor** [comment]
Any update on this? It would be very good to have this fix merged @drieks

**Comment by drieks** [comment]
Hi, I'm really sorry, I don't have much time at the moment. one possibility would be to temporarily expand the antlr-kotlin support. but I'm still not sure why publishing to maven central doesn't work. in the end not all jar files that were necessary were created. and I think we will run into the same problem with this library here, because it seems to be a multiplatform publishing issue.

**Pull request merged**
